### ISSUE TITLE
Read log file with gz extension

### ISSUE THREAD

**Issue by hwhsu** [cgivre/drill-logfile-plugin#1]
Is the plugin support .gz extension? Thanks~

**Comment by cgivre** [comment]
I'll take a look.  I'm adding some functionality to this and submitting it for inclusion in the next version of Drill.  I'm adding the ability to specify data types and dates/times.

**Comment by hwhsu** [comment]
Thank you for your reply. I try to add hdfs CompressionCodecFactory and CompressionCodec for the reader of the constructor "LogRecordReader". Now I can read the log file with the .gz extension successfully!

**Comment by cgivre** [comment]
Can you share the code?

**Comment by cgivre** [comment]
Actually, please submit a PR to this plugin. 
— C

**Comment by hwhsu** [comment]
Sure, but I'm a newbie in drill. Not sure they are good enough.

**Comment by cgivre** [comment]
Merged
